language: python

python:
  - 2.7
  - 3.4

addons:
  apt:
    packages:
      - python-numpy
      - python3-numpy

install:
  - pip install --upgrade pip
  - pip install bokeh

script:
  python setup.py test
